# Author: Peter Kulisov
# Copyright: Peter Kulisov <peter.kulisov@gmail.com>
# If there are any issues contact me on the email above.
#
# Version 1.0
# Date: 11/08/2022
[tool.black]
line-length = 120
target-version = ['py38']
include = '\.pyi?$'
[tool.isort]
line_length = 120
