# Author: Peter Kulisov
# Copyright: Peter Kulisov <peter.kulisov@gmail.com>
# If there are any issues contact me on the email above.
#
# Version 1.0
# Date: 11/08/2022
version: '2.4'

volumes:
  static_volume:

services:

  nginx:
    image: peterk/nginx
    build: ../peterk/nginx
    volumes:
      - static_volume:/code/staticfiles
    ports:
      - 80:80
    depends_on:
      - web


  web:
    restart: always
    image: peterk/web
    build:
      context: ../peterk
      dockerfile: ./Docker/Dockerfile.local
    expose:
      - 8000
    # depends_on:
    #   - db
    volumes:
      # - ../peterk:/code
      - static_volume:/code/staticfiles
    env_file:
      - ../peterk/.env.prod
